name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Download
        run: go mod download
      - name: Test all
        run: go test -v ./...
